web:
  image: hitalos/laravel:latest
  ports:
  - 80:80
  volumes:
  - ./:/var/www
  links:
  - db
  environment:
    DB_HOST: db
    DB_DATABASE: app_db
    DB_USERNAME: homestead
    DB_PASSWORD: secret
    DB_CONNECTION: mysql
db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always

  environment:
    # with mysql
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: app_db
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret

    # with postgres
    #POSTGRES_DB: app_db
    #POSTGRES_USER: homestead
    #POSTGRES_PASSWORD: secret
